/**
 * Market expansion data - Top 30 markets for summer camp expansion
 * Based on research from markets.md analyzing family demographics,
 * household income, population growth, and market characteristics.
 */

export interface ExpansionMarket {
  key: string; // Unique identifier like "seattle-wa"
  name: string;
  state: string;
  tier: 1 | 2 | 3;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  timezone: string;
  suggestedDomains: string[]; // Potential domain names to check
  suggestedBrandName: string; // e.g., "SEA Camps"
  keyStats: string;
  whyStrong: string;
}

export const EXPANSION_MARKETS: ExpansionMarket[] = [
  // ============ TIER 1: Premier Markets ============
  {
    key: "dallas-fort-worth-tx",
    name: "Dallas-Fort Worth",
    state: "TX",
    tier: 1,
    coordinates: { latitude: 32.7767, longitude: -96.7970 },
    timezone: "America/Chicago",
    suggestedDomains: ["dfwcamps.com", "dallascamps.com", "dfwsummercamps.com"],
    suggestedBrandName: "DFW Camps",
    keyStats: "+779K people (12.5% growth), affluent suburbs like Frisco",
    whyStrong: "Explosive growth, affluent suburbs (Plano, Frisco), tech jobs",
  },
  {
    key: "seattle-wa",
    name: "Seattle",
    state: "WA",
    tier: 1,
    coordinates: { latitude: 47.6062, longitude: -122.3321 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["seacamps.com", "seattlecamps.com", "pnwcamps.com"],
    suggestedBrandName: "SEA Camps",
    keyStats: "$221,579 median family income",
    whyStrong: "Highest family incomes in US, tech hub, dual-earner families",
  },
  {
    key: "houston-tx",
    name: "Houston",
    state: "TX",
    tier: 1,
    coordinates: { latitude: 29.7604, longitude: -95.3698 },
    timezone: "America/Chicago",
    suggestedDomains: ["houcamps.com", "houstoncamps.com", "htxcamps.com"],
    suggestedBrandName: "HOU Camps",
    keyStats: "+659K people (13.9% growth)",
    whyStrong: "Fastest growing large metro, massive family population",
  },
  {
    key: "san-francisco-bay-area-ca",
    name: "San Francisco Bay Area",
    state: "CA",
    tier: 1,
    coordinates: { latitude: 37.7749, longitude: -122.4194 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["sfbaycamps.com", "bayareacamps.com", "sfcamps.com"],
    suggestedBrandName: "Bay Area Camps",
    keyStats: "$222,836 median family income",
    whyStrong: "Highest incomes, but competition from ActivityHero",
  },
  {
    key: "denver-co",
    name: "Denver",
    state: "CO",
    tier: 1,
    coordinates: { latitude: 39.7392, longitude: -104.9903 },
    timezone: "America/Denver",
    suggestedDomains: ["dencamps.com", "denvercamps.com", "milehicamps.com"],
    suggestedBrandName: "DEN Camps",
    keyStats: "Growing tech hub, outdoor culture",
    whyStrong: "Rising tech hub, affluent families, similar to Portland culture",
  },
  {
    key: "boston-ma",
    name: "Boston",
    state: "MA",
    tier: 1,
    coordinates: { latitude: 42.3601, longitude: -71.0589 },
    timezone: "America/New_York",
    suggestedDomains: ["boscamps.com", "bostoncamps.com", "beantowncamps.com"],
    suggestedBrandName: "BOS Camps",
    keyStats: "Biotech/education hub",
    whyStrong: "Affluent families, dual-earner professionals, long summers",
  },
  {
    key: "washington-dc",
    name: "Washington DC Metro",
    state: "DC",
    tier: 1,
    coordinates: { latitude: 38.9072, longitude: -77.0369 },
    timezone: "America/New_York",
    suggestedDomains: ["dccamps.com", "dmvcamps.com", "novacamps.com"],
    suggestedBrandName: "DC Camps",
    keyStats: "High federal/contractor incomes",
    whyStrong: "Dual-income households, excellent schools focus",
  },
  {
    key: "atlanta-ga",
    name: "Atlanta",
    state: "GA",
    tier: 1,
    coordinates: { latitude: 33.7490, longitude: -84.3880 },
    timezone: "America/New_York",
    suggestedDomains: ["atlcamps.com", "atlantacamps.com", "peachcamps.com"],
    suggestedBrandName: "ATL Camps",
    keyStats: "Major Southern hub",
    whyStrong: "Corporate relocations, growing suburbs, diverse population",
  },
  {
    key: "phoenix-mesa-az",
    name: "Phoenix-Mesa",
    state: "AZ",
    tier: 1,
    coordinates: { latitude: 33.4484, longitude: -112.0740 },
    timezone: "America/Phoenix",
    suggestedDomains: ["phxcamps.com", "phoenixcamps.com", "azcamps.com"],
    suggestedBrandName: "PHX Camps",
    keyStats: "+85K people 2023-24",
    whyStrong: "Year-round camp season, explosive suburb growth (Queen Creek)",
  },
  {
    key: "minneapolis-st-paul-mn",
    name: "Minneapolis-St. Paul",
    state: "MN",
    tier: 1,
    coordinates: { latitude: 44.9778, longitude: -93.2650 },
    timezone: "America/Chicago",
    suggestedDomains: ["mspcamps.com", "twincitycamps.com", "mncamps.com"],
    suggestedBrandName: "MSP Camps",
    keyStats: "$132,055 median family income",
    whyStrong: "#2 ranked metro for families, highest income among top family metros",
  },

  // ============ TIER 2: High-Growth Family Markets ============
  {
    key: "austin-tx",
    name: "Austin",
    state: "TX",
    tier: 2,
    coordinates: { latitude: 30.2672, longitude: -97.7431 },
    timezone: "America/Chicago",
    suggestedDomains: ["atxcamps.com", "austincamps.com", "keepaustincamps.com"],
    suggestedBrandName: "ATX Camps",
    keyStats: "\"Silicon Hills\"",
    whyStrong: "Young tech families, culture similar to Portland",
  },
  {
    key: "salt-lake-city-ut",
    name: "Salt Lake City",
    state: "UT",
    tier: 2,
    coordinates: { latitude: 40.7608, longitude: -111.8910 },
    timezone: "America/Denver",
    suggestedDomains: ["slccamps.com", "utahcamps.com", "saltlakecamps.com"],
    suggestedBrandName: "SLC Camps",
    keyStats: "53% population under 35, 28.4% under 18",
    whyStrong: "Youngest large metro, highest % of children",
  },
  {
    key: "charlotte-nc",
    name: "Charlotte",
    state: "NC",
    tier: 2,
    coordinates: { latitude: 35.2271, longitude: -80.8431 },
    timezone: "America/New_York",
    suggestedDomains: ["cltcamps.com", "charlottecamps.com", "qccamps.com"],
    suggestedBrandName: "CLT Camps",
    keyStats: "6th fastest growing major city",
    whyStrong: "Strong job market, growing suburbs",
  },
  {
    key: "raleigh-durham-nc",
    name: "Raleigh-Durham",
    state: "NC",
    tier: 2,
    coordinates: { latitude: 35.7796, longitude: -78.6382 },
    timezone: "America/New_York",
    suggestedDomains: ["rducamps.com", "trianglecamps.com", "raleighcamps.com"],
    suggestedBrandName: "RDU Camps",
    keyStats: "33K growth since 2020",
    whyStrong: "Research Triangle, highly educated families",
  },
  {
    key: "nashville-tn",
    name: "Nashville",
    state: "TN",
    tier: 2,
    coordinates: { latitude: 36.1627, longitude: -86.7816 },
    timezone: "America/Chicago",
    suggestedDomains: ["bnacamps.com", "nashcamps.com", "nashvillecamps.com"],
    suggestedBrandName: "BNA Camps",
    keyStats: "Franklin, Thompson's Station booming",
    whyStrong: "Suburb growth, corporate relocations",
  },
  {
    key: "san-diego-ca",
    name: "San Diego",
    state: "CA",
    tier: 2,
    coordinates: { latitude: 32.7157, longitude: -117.1611 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["sancamps.com", "sdcamps.com", "sandiegocamps.com"],
    suggestedBrandName: "SAN Camps",
    keyStats: "Affluent suburbs (Rancho Santa Fe, Del Mar)",
    whyStrong: "Outdoor culture, year-round activities",
  },
  {
    key: "tampa-bay-fl",
    name: "Tampa Bay",
    state: "FL",
    tier: 2,
    coordinates: { latitude: 27.9506, longitude: -82.4572 },
    timezone: "America/New_York",
    suggestedDomains: ["tbcamps.com", "tampacamps.com", "tampabcamps.com"],
    suggestedBrandName: "TPA Camps",
    keyStats: "Florida growth corridor",
    whyStrong: "Growing family population, affordable",
  },
  {
    key: "san-jose-south-bay-ca",
    name: "San Jose/South Bay",
    state: "CA",
    tier: 2,
    coordinates: { latitude: 37.3382, longitude: -121.8863 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["sjccamps.com", "sanjosecamps.com", "southbaycamps.com"],
    suggestedBrandName: "SJC Camps",
    keyStats: "$201,721 median family income",
    whyStrong: "Top 3 family incomes, tech hub",
  },
  {
    key: "orange-county-ca",
    name: "Orange County",
    state: "CA",
    tier: 2,
    coordinates: { latitude: 33.7175, longitude: -117.8311 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["soccamps.com", "occamps.com", "orangecountycamps.com"],
    suggestedBrandName: "OC Camps",
    keyStats: "Irvine, Newport Beach",
    whyStrong: "Affluent families, excellent schools",
  },
  {
    key: "cincinnati-oh",
    name: "Cincinnati",
    state: "OH",
    tier: 2,
    coordinates: { latitude: 39.1031, longitude: -84.5120 },
    timezone: "America/New_York",
    suggestedDomains: ["cvgcamps.com", "cinticamps.com", "cincinnaticamps.com"],
    suggestedBrandName: "CVG Camps",
    keyStats: "$106,971 median family income, top 3 for families",
    whyStrong: "Affordable + high income combo",
  },

  // ============ TIER 3: Strong Regional Markets ============
  {
    key: "chicago-suburbs-il",
    name: "Chicago Suburbs (DuPage Co.)",
    state: "IL",
    tier: 3,
    coordinates: { latitude: 41.8488, longitude: -88.0905 },
    timezone: "America/Chicago",
    suggestedDomains: ["chicamps.com", "chicagosubcamps.com", "dupagecamps.com"],
    suggestedBrandName: "CHI Camps",
    keyStats: "$198,836 median income (Western Springs)",
    whyStrong: "Best county for families in IL, affluent",
  },
  {
    key: "san-antonio-tx",
    name: "San Antonio",
    state: "TX",
    tier: 3,
    coordinates: { latitude: 29.4241, longitude: -98.4936 },
    timezone: "America/Chicago",
    suggestedDomains: ["satcamps.com", "sanantoniocamps.com", "alamocamps.com"],
    suggestedBrandName: "SAT Camps",
    keyStats: "Large metro, affordable",
    whyStrong: "Big family population, military families",
  },
  {
    key: "columbus-oh",
    name: "Columbus",
    state: "OH",
    tier: 3,
    coordinates: { latitude: 39.9612, longitude: -82.9988 },
    timezone: "America/New_York",
    suggestedDomains: ["cmhcamps.com", "columbuscamps.com", "614camps.com"],
    suggestedBrandName: "CMH Camps",
    keyStats: "Growing tech scene",
    whyStrong: "Ohio State ecosystem, affordable",
  },
  {
    key: "indianapolis-in",
    name: "Indianapolis (Carmel/Zionsville)",
    state: "IN",
    tier: 3,
    coordinates: { latitude: 39.7684, longitude: -86.1581 },
    timezone: "America/Indiana/Indianapolis",
    suggestedDomains: ["indcamps.com", "indycamps.com", "napanowcamps.com"],
    suggestedBrandName: "IND Camps",
    keyStats: "Suburb infrastructure growing",
    whyStrong: "#2 best place to raise family (Overland Park peer)",
  },
  {
    key: "orlando-fl",
    name: "Orlando",
    state: "FL",
    tier: 3,
    coordinates: { latitude: 28.5383, longitude: -81.3792 },
    timezone: "America/New_York",
    suggestedDomains: ["mcocamps.com", "orlandocamps.com", "centralflcamps.com"],
    suggestedBrandName: "MCO Camps",
    keyStats: "Family destination market",
    whyStrong: "Tourism-adjacent, growing population",
  },
  {
    key: "kansas-city-mo",
    name: "Kansas City (Overland Park, KS)",
    state: "MO",
    tier: 3,
    coordinates: { latitude: 39.0997, longitude: -94.5786 },
    timezone: "America/Chicago",
    suggestedDomains: ["kcicamps.com", "kccamps.com", "kansascitycamps.com"],
    suggestedBrandName: "KC Camps",
    keyStats: "$149K+ median family income adjusted",
    whyStrong: "2nd best place for families nationally",
  },
  {
    key: "sacramento-ca",
    name: "Sacramento",
    state: "CA",
    tier: 3,
    coordinates: { latitude: 38.5816, longitude: -121.4944 },
    timezone: "America/Los_Angeles",
    suggestedDomains: ["smfcamps.com", "sacracamps.com", "sacramentocamps.com"],
    suggestedBrandName: "SAC Camps",
    keyStats: "Bay Area spillover",
    whyStrong: "Families priced out of SF moving here",
  },
  {
    key: "jacksonville-fl",
    name: "Jacksonville",
    state: "FL",
    tier: 3,
    coordinates: { latitude: 30.3322, longitude: -81.6557 },
    timezone: "America/New_York",
    suggestedDomains: ["jaxcamps.com", "jacksonvillecamps.com", "904camps.com"],
    suggestedBrandName: "JAX Camps",
    keyStats: "Fast growth",
    whyStrong: "Affordable Florida alternative",
  },
  {
    key: "pittsburgh-pa",
    name: "Pittsburgh",
    state: "PA",
    tier: 3,
    coordinates: { latitude: 40.4406, longitude: -79.9959 },
    timezone: "America/New_York",
    suggestedDomains: ["pitcamps.com", "pittsburghcamps.com", "steelcitycamps.com"],
    suggestedBrandName: "PIT Camps",
    keyStats: "Stable, family-focused suburbs",
    whyStrong: "Tech revival, affordable, good schools",
  },
  {
    key: "ann-arbor-mi",
    name: "Ann Arbor",
    state: "MI",
    tier: 3,
    coordinates: { latitude: 42.2808, longitude: -83.7430 },
    timezone: "America/Detroit",
    suggestedDomains: ["a2camps.com", "annarborcamps.com", "washtenawcamps.com"],
    suggestedBrandName: "A2 Camps",
    keyStats: "University town, educated population",
    whyStrong: "Strong schools, dual-earner academic families",
  },
];

// Helper functions
export function getExpansionMarketByKey(key: string): ExpansionMarket | undefined {
  return EXPANSION_MARKETS.find((m) => m.key === key);
}

export function getExpansionMarketsByTier(tier: 1 | 2 | 3): ExpansionMarket[] {
  return EXPANSION_MARKETS.filter((m) => m.tier === tier);
}

export function getAllExpansionMarketKeys(): string[] {
  return EXPANSION_MARKETS.map((m) => m.key);
}
